// run this script from the root of the project
// bash: node cloudinaryUrlsGenerator.js
// generates the cloudinary urls from local IMAGES_DIRS to cloudinary FOLDER and saves the urls to URLS_FILE
// MUST HAVE NODE.JS INSTALLED. also, npm install cloudinary & npm install dotenv
// Script adds new URLs to existing JS file or creates the js file, if it doesn't exist

import { v2 as cloudinary } from 'cloudinary'
import { config } from 'dotenv'
import fs from 'fs'
import path from 'path'

config()

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET
})

const FOLDER = 'sumit-portfolio/assets/greenfield/screens/'
const IMAGES_DIRS = [
  // './public/',
  // './public/previews/',
  // './public/screens/',
  './public/screens/greenfield-screens/',
  // './public/projects/',
  // './public/projects/interior/images/',
]
const URLS_FILE = './src/data/cloudinary-urls.js'

const SUPPORTED = ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.svg', '.mp4', '.mov', '.avi', '.webm', '.mkv']
const VIDEO_EXTS = ['.mp4', '.mov', '.avi', '.webm', '.mkv']

const toSafeKey = (name) => name.replace(/-/g, '_').replace(/\s+/g, '_')

const getOptimizedUrl = (url, isVideo) => {
  const params = isVideo
    ? 'f_auto,q_auto,vc_auto,fl_immutable_cache'
    : 'f_auto,q_auto,fl_immutable_cache'
  return url.replace('/upload/', `/upload/${params}/`)
}

// Load existing URLs if file exists
let urls = {}
if (fs.existsSync(URLS_FILE)) {
  const content = fs.readFileSync(URLS_FILE, 'utf-8')
  const matches = [...content.matchAll(/^\s+(\w+):\s+'(.+?)',$/gm)]
  matches.forEach(([, key, val]) => urls[key] = val)
  console.log(`Loaded ${Object.keys(urls).length} existing URLs from ${URLS_FILE}`)
}

let uploaded = 0
let skipped = 0

const files = IMAGES_DIRS.flatMap(dir =>
  fs.existsSync(dir)
    ? fs.readdirSync(dir)
      .filter(f => SUPPORTED.includes(path.extname(f).toLowerCase()))
      .map(f => ({ filename: f, dir }))
    : []
)

for (const { filename, dir } of files) {
  const filepath = path.join(dir, filename)
  const rawName = path.parse(filename).name
  const name = toSafeKey(rawName)
  const ext = path.extname(filename).toLowerCase()
  const isVideo = VIDEO_EXTS.includes(ext)

  if (urls[name]) {
    console.log(`  - skipping ${filename} (already uploaded as '${name}')`)
    skipped++
    continue
  }

  console.log(`Uploading ${filename}...`)

  try {
    const result = await cloudinary.uploader.upload(filepath, {
      folder: FOLDER,
      public_id: rawName,
      overwrite: false,
      resource_type: isVideo ? 'video' : 'image',
    })

    urls[name] = getOptimizedUrl(result.secure_url, isVideo)
    console.log(`  ✓ ${urls[name]}`)
    uploaded++
  } catch (e) {
    console.log(`  ✗ ${filename} - ${e.message}`)
  }
}

const entries = Object.entries(urls)
  .map(([key, val]) => `  ${key}: '${val}',`)
  .join('\n')

const output = `// Auto-generated by cloudinaryUrlsGenerator.js - do not edit manually\n\nexport const CLD_ASSETS = {\n${entries}\n};\n`

fs.writeFileSync(URLS_FILE, output)

console.log(`\nDone! ${uploaded} uploaded, ${skipped} skipped.`)
console.log(`URLs saved to ${URLS_FILE}`)